config/routes.rb
Rails.application.routes.draw do
    root to: "toppages#index"
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get "signup", to: "users#new"
    resources :users, only: [:show, :new, :create]do
      member do
        get :favorites
      end
    end
    
    resources :foods
    resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :food
  
  validates :user_id, presence: true
  validates :food_id, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 255 }
  validates :calorie, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than: 1000 }
  #validates :image_url, presence: true, length: { maximum: 255 }
  validates :comment, presence: true, length: { maximum: 255 }

end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    
    has_secure_password
    
    has_many :foods
    
    has_many :favorites
    has_many :favorite_foods, through: :favorites, source: :food
    
    
    def favorite(food)
        self.favorites.find_or_create_by(food_id: food.id)
    end
    
    def unfavorite(food)
        favorite = self.favorites.find_by(food_id: food.id)
        favorite.destroy if favorite
    end
        
    def favorite?(food)
        self.favorite_foods.include?(food)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in

  def create
    food = Food.find(params[:food_id])
    current_user.favorite(food)
    flash[:success] = "お気に入りに登録しました。"
    redirect_back(fallback_location: root_url)
  end

  def destroy
    food = Food.find(params[:food_id])
    current_user.unfavorite(food)
    flash[:success] = "お気に入りを解除しました。"
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def new
    @food = Food.new
  end
  
  def show
    @food = Food.find(params[:id])
  end
  
  def edit
    @food = Food.find(params[:id])
  end
  
  def update
    @food = Food.find(params[:id])

    if @food.update(food_params)
      flash[:success] = '商品を編集しました。'
      redirect_to @food
    else
      flash.now[:danger] = '編集に失敗しました。'
      render :edit
    end
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      flash[:success] = '商品を投稿しました。'
      redirect_to root_url
    else
      @foods = current_user.foods.order('created_at DESC')
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    flash[:success] = '商品を削除しました。'
    redirect_to root_url
  end
  
  private

  def food_params
    params.require(:food).permit(:name, :calorie, :image_url, :comment)
  end
  
  def correct_user
    @food = current_user.foods.find_by(id: params[:id])
    unless @food
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @foods = Food.all.order(calorie: :desc)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  def show
    @user = User.find(params[:id])
    @foods = current_user.foods.order('created_at DESC')
    @food = Food.find(params[:id])
    @favorites = @user.favorite_foods
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.favorite_foods
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
    end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(food) %>
    <%= form_for(current_user.favorites.find_by(food_id: food.id),html: { method: :delete}) do |f| %>
      <%= hidden_field_tag :food_id, food.id %>
      <%= f.submit "お気に入りから外す", class: "btn btn-danger" %>
    <% end %>
<% else %>
    <%= form_for(current_user.favorites.build) do |f| %>
      <%= hidden_field_tag :food_id, food.id %>
      <%= f.submit "この商品をお気に入りする", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/foods/_foods.html.erb
<div class="row media-list">
  <% foods.each do |food| %>
    <div class="col-sm-3">
      <div class="box5">
      <div class="media-center">
        <div class="text-center">
          <div class="h2"><%= food.calorie %><span class="text-muted"> kcal</span></div>
        </div>
         <div class="icon text-center">
          <%= link_to image_tag('/onigiri.png', { :border => '0', :alt => '商品画像'}), food_path(food) %>
          </div>
        <div class="text-center">
          <div class="h3"><%= link_to food.name ,food_path(food), :style=>"color:#fff;" %></div>
        </div>
      </div>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="container">
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
       <div class="text-center">
         商品を編集する
       </div>
    </div>
    <div class="panel-body">
      <%= form_for(@food) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
       <div class="icon text-center">
         <img src="/sara.png" alt="お皿">
       </div>
       <aside class="col-xs-4 col-xs-offset-1">
         
          <div class="form-group">
            <%= f.label :name, '商品名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :calorie, 'カロリー' %>
            <%= f.text_field :calorie, class: 'form-control'%>
          </div>
        </aside>
        <div class="col-xs-offset-1 col-xs-5">
          <div class="form-group">
            <%= f.label :comment, 'コメント' %>
            <%= f.text_area :comment, class: 'form-control', rows: 5 %>
          </div>
          <div class="text-right">
            <%= f.submit '編集を完了する', class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/foods/new.html.erb
<div class="container">
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
       <div class="text-center">
         商品を投稿する
       </div>
    </div>
    <div class="panel-body">
      <%= form_for(@food) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
       <div class="icon text-center">
         <img src="/sara.png" alt="お皿">
       </div>
       <aside class="col-xs-4 col-xs-offset-1">
         
          <div class="form-group">
            <%= f.label :name, '商品名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :calorie, 'カロリー' %>
            <%= f.text_field :calorie, class: 'form-control'%>
          </div>
        </aside>
        <div class="col-xs-offset-1 col-xs-5">
          <div class="form-group">
            <%= f.label :comment, 'コメント' %>
            <%= f.text_area :comment, class: 'form-control', rows: 5 %>
          </div>
          <div class="text-right">
            <%= f.submit '投稿する', class: 'btn btn-success' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/foods/show.html.erb
<div class="container">
 <div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <div class="text-center">
        商品の詳細
      </div>
    </div>
    <div class="panel-body">
       <div class="food-profile">
         <asside class="col-xs-5">
           <div class="word text-center">
            <%= @food.name %>
           </div>
           <div class="icon text-center">
            <img src="/sara.png" alt="" >
           </div>
           <div class="h2 text-center">
            <%= @food.calorie %><span class="text-muted">kcal</span>
           </div>
         </asside>
         <div class="col-xs-6">
           <div class="word2">comment</div>
           <div class="box2">
             <div class="name text-left"><p><%= @food.comment %></p></div>
           </div>
         </div>
         </div>
       </div>
       <div class="panel-footer">
         <div class="icon text-center">
         <% if current_user == @food.user %>
            <%= link_to "この商品を消す", @food , method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
            <%= link_to 'この商品を編集する', edit_food_path(@food), class: 'btn btn-primary' %>
        <% else %>
            <%= render "favorites/favorite_button", food: @food %>
         <% end %>
         </div>
   </div>
  </div>
 </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
   <div class="alert alert-warning">
       <ul>
           <% model.errors.full_messages.each do |message| %>
             <il><%= message %></il>
           <% end %>
       </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">© 2018 CALORIST.</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to '商品を投稿', new_food_path %>
                </a>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'マイページ', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%#= link_to '新規登録', signup_path %></li>
            <li><%#= link_to 'ログイン', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Calorists</title>
    
    
    <%= csrf_meta_tags %>
    
      <!-- Bootstrap CSS-->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <!-- app/assets/stylesheets -->
      
      
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
      <!-- jQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <!-- Bootstrap JavaScript-->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <!-- app/assets/javascripts-->
      
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
<div id="header-fixed">
<header class="header header--center">
  <div id ="inner-header">
    
<%= yield :cover %>
  <p id="logo">
    <a href="/"><img src="/title.png" class="title"></a>
  </p>
   </header>
   <% if logged_in? %>
      <%= render 'layouts/navbar' %>
   <% end %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      


      
  <%= yield %>

 <%= render 'layouts/footer' %>
 
    </div>
    </div>
 
  
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
<div class="row">
   
    <div class="col-xs-12">
      <%= render 'foods/foods', foods: @foods %>
      </div>
  </div>
<% else %>
<body id="index">
  <div class="box5">
  <div class="bg-mask">
<div class="wrapper">
  <div class="inside">
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        
          <%= link_to '新規登録', signup_path,class: 'btn btn-lg btn-primary' %>
          <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
</div>
</div>
</body>
<% end %>

app/views/users/_favorites.html.erb
<% if favorites.any? %>
  <ul class="media-list">
      <% favorites.each do |food| %>
        <li class="media">
            <div class="media-left">
                <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
            </div>
            <div class="media-body">
                <div>
                    <%= food.name %>
                </div>
                <div>
                  <%= link_to "favorite", root_url, method: :get, data: { confirm: "You sure?" }, class: "btn btn-primary btn-xs" %>
                  <% if current_user == favorite.user %>
                    <%= link_to "Delate", food, method: :deleate, data: { confirm: "You sure?" }, class: "btn btn-danger btn-xs" %>
                  <% end %>
                </div>
            </div>
        </li>
      <% end %>
    </ul>
<% end %>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-xs-4">
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="name text-center">
    <h1><%= @user.name %></h1>
  </div>
  
</div>
</aside>
<div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>投稿したもの <% end %></li>
      <li class="<%= "active" if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り <% end %></li>
    </ul>
    <%= render 'foods/foods', foods: @favorites %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="box5">
      <div class="word2 text-center">会員登録</div>
       <div class="login-form">
        <%= form_for(@user) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-center">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="box3">
      <div class="user">
       <div class="word text-center">
         name: <%= @user.name %>
       </div>
       <!--<div class="icon text-center">-->
         <!--<img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">-->
       <!--</div>-->
      </div>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="box3">
     <div class="user-profile">
       <!--<ul class="nav nav-tabs nav-justified">-->
       <!--<li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>投稿したもの <% end %></li>-->
       <!--<li class="<%= "active" if current_page?(favorites_user_path(@user)) %>"><%= link_to favorites_user_path(@user) do %>お気に入り <% end %></li>-->
       <!--</ul>-->
       <div class="profile-text text-center">投稿したもの</div>
       <%= render 'foods/foods', foods: @foods %>
       </div>
        </div>
       <div class="box3">
         <div class="user-profile">
          <div class="profile-text text-center">お気に入り</div>
         <%= render 'foods/foods', foods: @favorites %>
       </div>
       </div>
    
     
     </div>
</div>